# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yappblocker < Formula
  desc "Kill distracting macOS apps on a schedule"
  homepage "https://github.com/mieubrisse/yappblocker"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mieubrisse/yappblocker/releases/download/v0.3.1/yappblocker_0.3.1_darwin_amd64.tar.gz"
    sha256 "e8baa9cccdce74dbd55186dded737657a846339f367f56d4c87a3315251a8110"

    define_method(:install) do
      bin.install "yappblocker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mieubrisse/yappblocker/releases/download/v0.3.1/yappblocker_0.3.1_darwin_arm64.tar.gz"
    sha256 "a186c93f3f5d4c4a532001f97e4dc140a4766b65e975a1faaaab9b6e3e3cb945"

    define_method(:install) do
      bin.install "yappblocker"
    end
  end

  def caveats
    <<~EOS
      ⚠️  To finish setup, run:

        yappblocker init

      This creates your config file and starts automatic enforcement.
    EOS
  end

  test do
    system "#{bin}/yappblocker", "--help"
  end
end
