# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yappblocker < Formula
  desc "Kill distracting macOS apps on a schedule"
  homepage "https://github.com/mieubrisse/yappblocker"
  version "0.3.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mieubrisse/yappblocker/releases/download/v0.3.2/yappblocker_0.3.2_darwin_amd64.tar.gz"
    sha256 "7e646323c082db5858ffd8d7beb458c40e0eb2fffb2dc8349300d4d01e531713"

    define_method(:install) do
      bin.install "yappblocker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mieubrisse/yappblocker/releases/download/v0.3.2/yappblocker_0.3.2_darwin_arm64.tar.gz"
    sha256 "424ab54fa4999b65a6746bce0e5c0eb7d410f2883282666b69277a8267dc429b"

    define_method(:install) do
      bin.install "yappblocker"
    end
  end

  def caveats
    <<~EOS
      ⚠️  To finish setup, run:

        yappblocker init

      This creates your config file and starts automatic enforcement.
    EOS
  end

  test do
    system "#{bin}/yappblocker", "--help"
  end
end
